#!/bin/bash

set -x

info() {
    echo -e "\033[1;33m[Info]    \033[0m $1"
}

error() {
    echo -e "\033[1;31m[Error]   \033[0m $1"
}

error_exit() {
    error "${1:-"Unknown Error"}. Error code is $?" 1>&2
    exit 1
}

cleanup() {
    info "Cleaning up..."
}

trap 'cleanup' EXIT


if [ "$BUILD_SOURCESDIRECTORY" = "" ]; then
    ENLISTMENT_ROOT=$(pwd)
else
    ENLISTMENT_ROOT=$BUILD_SOURCESDIRECTORY
fi

echo "Enlistment root is $ENLISTMENT_ROOT"

# set up test environment variables
#
if [ $# -eq 0 ]; then
    ENV_FILE=/tmp/.test.env
else
    ENV_FILE=$1
fi

source ${ENV_FILE}

export BOOTSTRAPPER_IMAGE=${SOURCE_DOCKER_REGISTRY}/${SOURCE_DOCKER_REPOSITORY}/arc-bootstrapper:${SOURCE_DOCKER_TAG}

echo "Building ${BuildBranch}"
echo "AZDATA_USERNAME ${AZDATA_USERNAME}"
echo "AZDATA_PASSWORD ${AZDATA_PASSWORD}"
echo "DOCKER_USERNAME ${DOCKER_USERNAME}"
echo "DOCKER_PASSWORD ${DOCKER_PASSWORD}"
echo "DOCKER_IMAGE_POLICY ${DOCKER_IMAGE_POLICY}"
echo "ACCEPT_EULA ${ACCEPT_EULA}"
echo "DEBIAN_FRONTEND ${DEBIAN_FRONTEND}"
echo "CLUSTER_NAME ${CLUSTER_NAME}"
echo "SUBSCRIPTION_ID ${SUBSCRIPTION_ID}"
echo "RESOURCE_GROUP_NAME ${RESOURCE_GROUP_NAME}"
echo "LOCATION ${LOCATION}"
echo "TEST_DATA_CONTROLLER_NAME ${TEST_DATA_CONTROLLER_NAME}"
echo "KUBERNETES_ENVIRONMENT ${KUBERNETES_ENVIRONMENT}"
echo "OPENSHIFT_APISERVER ${OPENSHIFT_APISERVER}"
echo "OPENSHIFT_USERNAME ${OPENSHIFT_USERNAME}"
echo "OPENSHIFT_PASSWORD ${OPENSHIFT_PASSWORD}"
echo "BOOTSTRAPPER_IMAGE ${BOOTSTRAPPER_IMAGE}"
echo "SOURCE_DOCKER_TAG ${SOURCE_DOCKER_TAG}"
echo "AZURE_CLUSTER_SUBSCRIPTION ${AZURE_CLUSTER_SUBSCRIPTION}"
echo "AZURE_CLUSTER_RESOURCEGROUP ${AZURE_CLUSTER_RESOURCEGROUP}"
echo "AZURE_CLUSTER_NAME ${AZURE_CLUSTER_NAME}"
echo "ARC_TEST_SP_NAME ${ARC_TEST_SP_NAME}"
echo "ARC_TEST_SP_PASSWORD ${ARC_TEST_SP_PASSWORD}"
echo "ARC_TEST_SP_TENANT ${ARC_TEST_SP_TENANT}"
